/**
 * `"Saadatu Hamu Aliyu"` -> `"SA"` (first + last word's first letter, middle
 * words ignored). Falls back to the first two characters of a single-word
 * name.
 *
 * Promoted here in Sprint 5 from a private helper inside `Header.tsx`
 * (Sprint 2) — `NewJoinersWidget`'s avatar initials need the exact same
 * algorithm (the wireframe's own `.jav` seed values, e.g. "Saadatu Hamu
 * Aliyu" -> "SA", "IT Admin" -> "IA", are generated by this same rule), and
 * a second component needing identical logic is exactly the point at which
 * a private per-file helper should become a shared utility instead of being
 * copy-pasted. `Header.tsx` now imports this instead of defining its own
 * copy; its behavior is unchanged.
 */
export function getInitials(displayName: string): string {
  const words = displayName.trim().split(/\s+/).filter(Boolean);
  if (words.length === 0) {
    return '';
  }
  if (words.length === 1) {
    return words[0]?.slice(0, 2).toUpperCase() ?? '';
  }
  const first = words[0]?.[0] ?? '';
  const last = words[words.length - 1]?.[0] ?? '';
  return `${first}${last}`.toUpperCase();
}
